const recipesData = {
  "meals": [
    {
      "idMeal": "52779",
      "strMeal": "Cream Cheese Tart",
      "strDrinkAlternate": null,
      "strCategory": "Starter",
      "strArea": "Unknown",
      "strInstructions": "Crust: make a dough from 250g flour (I like mixing different flours like plain and wholegrain spelt flour), 125g butter, 1 egg and a pinch of salt, press it into a tart form and place it in the fridge. Filling: stir 300g cream cheese and 100ml milk until smooth, add in 3 eggs, 100g grated parmesan cheese and season with salt, pepper and nutmeg. Take the crust out of the fridge and prick the bottom with a fork. Pour in the filling and bake at 175 degrees C for about 25 minutes. Cover the tart with some aluminium foil after half the time. In the mean time, slice about 350g mini tomatoes. In a small pan heat 3tbsp olive oil, 3tbsp white vinegar, 1 tbsp honey, salt and pepper and combine well. Pour over the tomato slices and mix well. With a spoon, place the tomato slices on the tart, avoiding too much liquid on it. Decorate with basil leaves and enjoy",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg",
      "strTags": "Tart,Savory",
      "strYoutube": "https://www.youtube.com/watch?v=UhQPwO4uymo",
      "strIngredient1": "Flour",
      "strIngredient2": "Butter",
      "strIngredient3": "Egg",
      "strIngredient4": "Salt",
      "strIngredient5": "Cheese",
      "strIngredient6": "Milk",
      "strIngredient7": "Eggs",
      "strIngredient8": "Parmesan Cheese",
      "strIngredient9": "Plum tomatoes",
      "strIngredient10": "White Vinegar",
      "strIngredient11": "Honey",
      "strIngredient12": "Basil",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "250g",
      "strMeasure2": "125g",
      "strMeasure3": "1",
      "strMeasure4": "Pinch",
      "strMeasure5": "300g",
      "strMeasure6": "100ml milk",
      "strMeasure7": "3",
      "strMeasure8": "100g",
      "strMeasure9": "350g",
      "strMeasure10": "3tbsp",
      "strMeasure11": "1 tbsp",
      "strMeasure12": "Topping",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": "https://www.instagram.com/p/BHyuMZ1hZX0",
      "dateModified": null
  },
  {
      "idMeal": "52841",
      "strMeal": "Creamy Tomato Soup",
      "strDrinkAlternate": null,
      "strCategory": "Starter",
      "strArea": "British",
      "strInstructions": "Put the oil, onions, celery, carrots, potatoes and bay leaves in a big casserole dish, or two saucepans. Fry gently until the onions are softened – about 10-15 mins. Fill the kettle and boil it.\r\nStir in the tomato purée, sugar, vinegar, chopped tomatoes and passata, then crumble in the stock cubes. Add 1 litre boiling water and bring to a simmer. Cover and simmer for 15 mins until the potato is tender, then remove the bay leaves. Purée with a stick blender (or ladle into a blender in batches) until very smooth. Season to taste and add a pinch more sugar if it needs it. The soup can now be cooled and chilled for up to 2 days, or frozen for up to 3 months.\r\nTo serve, reheat the soup, stirring in the milk – try not to let it boil. Serve in small bowls with cheesy sausage rolls.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/stpuws1511191310.jpg",
      "strTags": "Baking",
      "strYoutube": "https://www.youtube.com/watch?v=lBhwjjUiFk4",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Onions",
      "strIngredient3": "Celery",
      "strIngredient4": "Carrots",
      "strIngredient5": "Potatoes",
      "strIngredient6": "Bay Leaf",
      "strIngredient7": "Tomato Puree",
      "strIngredient8": "Sugar",
      "strIngredient9": "White Vinegar",
      "strIngredient10": "Chopped Tomatoes",
      "strIngredient11": "Passata",
      "strIngredient12": "Vegetable Stock Cube",
      "strIngredient13": "Whole Milk",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 tbsp",
      "strMeasure2": "2 chopped",
      "strMeasure3": "2 sticks",
      "strMeasure4": "300g",
      "strMeasure5": "500g",
      "strMeasure6": "4",
      "strMeasure7": "5 tblsp ",
      "strMeasure8": "2 tblsp ",
      "strMeasure9": "2 tblsp ",
      "strMeasure10": "1½ kg",
      "strMeasure11": "500g",
      "strMeasure12": "3",
      "strMeasure13": "400ml",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/2604646/creamy-tomato-soup",
      "dateModified": null
  },
  {
      "idMeal": "52957",
      "strMeal": "Fruit and Cream Cheese Breakfast Pastries",
      "strDrinkAlternate": null,
      "strCategory": "Breakfast",
      "strArea": "American",
      "strInstructions": "Preheat oven to 400ºF (200ºC), and prepare two cookie sheets with parchment paper. In a bowl, mix cream cheese, sugar, and vanilla until fully combined. Lightly flour the surface and roll out puff pastry on top to flatten. Cut each sheet of puff pastry into 9 equal squares. On the top right and bottom left of the pastry, cut an L shape approximately ½ inch (1 cm) from the edge.\r\nNOTE: This L shape should reach all the way down and across the square, however both L shapes should not meet at the ends. Your pastry should look like a picture frame with two corners still intact.\r\nTake the upper right corner and fold down towards the inner bottom corner. You will now have a diamond shape.\r\nPlace 1 to 2 teaspoons of the cream cheese filling in the middle, then place berries on top.\r\nRepeat with the remaining pastry squares and place them onto the parchment covered baking sheet.\r\nBake for 15-20 minutes or until pastry is golden brown and puffed.\r\nEnjoy!\r\n",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1543774956.jpg",
      "strTags": "Breakfast,Summer",
      "strYoutube": "",
      "strIngredient1": "Cream Cheese",
      "strIngredient2": "Sugar",
      "strIngredient3": "Vanilla Extract",
      "strIngredient4": "Flour",
      "strIngredient5": "Puff Pastry",
      "strIngredient6": "Strawberries",
      "strIngredient7": "Raspberries",
      "strIngredient8": "Blackberries",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1 1/4 oz ",
      "strMeasure2": "1 1/4 cup",
      "strMeasure3": "1 teaspoon",
      "strMeasure4": "",
      "strMeasure5": "2",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": "",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "",
      "dateModified": null
  },
      {
          "idMeal": "52823",
          "strMeal": "Salmon Prawn Risotto",
          "strDrinkAlternate": null,
          "strCategory": "Seafood",
          "strArea": "Italian",
          "strInstructions": "Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\r\nAdd the rice and stir to coat all the grains in the butter\r\nAdd the wine and cook gently stirring until it is absorbed\r\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\r\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\r\nServe scattered with the Parmesan and seasonal vegetables.\r\nGrill the salmon and gently place onto the risotto with the prawns and asparagus",
          "strMealThumb": "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
          "strTags": "Fish",
          "strYoutube": "https://www.youtube.com/watch?v=V2PMvBv52IE",
          "strIngredient1": "butter",
          "strIngredient2": "onion",
          "strIngredient3": "rice",
          "strIngredient4": "white wine",
          "strIngredient5": "vegetable stock",
          "strIngredient6": "lemon",
          "strIngredient7": "King Prawns",
          "strIngredient8": "salmon",
          "strIngredient9": "asparagus",
          "strIngredient10": "black pepper",
          "strIngredient11": "Parmesan",
          "strIngredient12": "",
          "strIngredient13": "",
          "strIngredient14": "",
          "strIngredient15": "",
          "strIngredient16": "",
          "strIngredient17": "",
          "strIngredient18": "",
          "strIngredient19": "",
          "strIngredient20": "",
          "strMeasure1": "50g/2oz",
          "strMeasure2": "1 finely chopped ",
          "strMeasure3": "150g",
          "strMeasure4": "125ml ",
          "strMeasure5": "1 litre hot",
          "strMeasure6": "The juice and zest of one",
          "strMeasure7": "240g large",
          "strMeasure8": "150g",
          "strMeasure9": "100g tips blanched briefly in boiling water",
          "strMeasure10": "ground",
          "strMeasure11": "50g shavings",
          "strMeasure12": "",
          "strMeasure13": "",
          "strMeasure14": "",
          "strMeasure15": "",
          "strMeasure16": "",
          "strMeasure17": "",
          "strMeasure18": "",
          "strMeasure19": "",
          "strMeasure20": "",
          "strSource": "http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus",
          "dateModified": null
      },
      {
          "idMeal": "52960",
          "strMeal": "Salmon Avocado Salad",
          "strDrinkAlternate": null,
          "strCategory": "Seafood",
          "strArea": "British",
          "strInstructions": "Season the salmon, then rub with oil. Mix the dressing ingredients together. Halve, stone, peel and slice the avocados. Halve and quarter the cucumber lengthways, then cut into slices. Divide salad, avocado and cucumber between four plates, then drizzle with half the dressing.\r\n\r\nHeat a non-stick pan. Add the salmon and fry for 3-4 mins on each side until crisp but still moist inside. Put a salmon fillet on top of each salad and drizzle over the remaining dressing. Serve warm.",
          "strMealThumb": "https://www.themealdb.com/images/media/meals/1549542994.jpg",
          "strTags": "Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,",
          "strYoutube": "https://www.youtube.com/watch?v=FJiu2S0Xap0",
          "strIngredient1": "Salmon",
          "strIngredient2": "Avocado",
          "strIngredient3": "Cucumber",
          "strIngredient4": "Spinach",
          "strIngredient5": "Mint",
          "strIngredient6": "Lime",
          "strIngredient7": "Honey",
          "strIngredient8": "Olive Oil",
          "strIngredient9": "",
          "strIngredient10": "",
          "strIngredient11": "",
          "strIngredient12": "",
          "strIngredient13": "",
          "strIngredient14": "",
          "strIngredient15": "",
          "strIngredient16": "",
          "strIngredient17": "",
          "strIngredient18": "",
          "strIngredient19": "",
          "strIngredient20": "",
          "strMeasure1": "400g",
          "strMeasure2": "3",
          "strMeasure3": "1",
          "strMeasure4": "400g",
          "strMeasure5": "4 tbs",
          "strMeasure6": "zest and juice of 1",
          "strMeasure7": "2 tsp",
          "strMeasure8": "3 tbs",
          "strMeasure9": "",
          "strMeasure10": "",
          "strMeasure11": "",
          "strMeasure12": "",
          "strMeasure13": "",
          "strMeasure14": "",
          "strMeasure15": "",
          "strMeasure16": "",
          "strMeasure17": "",
          "strMeasure18": "",
          "strMeasure19": "",
          "strMeasure20": "",
          "strSource": "https://www.bbcgoodfood.com/recipes/4521/salmon-avocado-and-cucumber-salad",
          "dateModified": null
      },
      {
          "idMeal": "52773",
          "strMeal": "Honey Teriyaki Salmon",
          "strDrinkAlternate": null,
          "strCategory": "Seafood",
          "strArea": "Japanese",
          "strInstructions": "Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.",
          "strMealThumb": "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
          "strTags": "Fish,Breakfast,DateNight",
          "strYoutube": "https://www.youtube.com/watch?v=4MpYuaJsvRw",
          "strIngredient1": "Salmon",
          "strIngredient2": "Olive oil",
          "strIngredient3": "Soy Sauce",
          "strIngredient4": "Sake",
          "strIngredient5": "Sesame Seed",
          "strIngredient6": "",
          "strIngredient7": "",
          "strIngredient8": "",
          "strIngredient9": "",
          "strIngredient10": "",
          "strIngredient11": "",
          "strIngredient12": "",
          "strIngredient13": "",
          "strIngredient14": "",
          "strIngredient15": "",
          "strIngredient16": null,
          "strIngredient17": null,
          "strIngredient18": null,
          "strIngredient19": null,
          "strIngredient20": null,
          "strMeasure1": "1 lb",
          "strMeasure2": "1 tablespoon",
          "strMeasure3": "2 tablespoons",
          "strMeasure4": "2 tablespoons",
          "strMeasure5": "4 tablespoons",
          "strMeasure6": "",
          "strMeasure7": "",
          "strMeasure8": "",
          "strMeasure9": "",
          "strMeasure10": "",
          "strMeasure11": "",
          "strMeasure12": "",
          "strMeasure13": "",
          "strMeasure14": "",
          "strMeasure15": "",
          "strMeasure16": null,
          "strMeasure17": null,
          "strMeasure18": null,
          "strMeasure19": null,
          "strMeasure20": null,
          "strSource": null,
          "dateModified": null
      },
      {
          "idMeal": "52962",
          "strMeal": "Salmon Eggs Eggs Benedict",
          "strDrinkAlternate": null,
          "strCategory": "Breakfast",
          "strArea": "American",
          "strInstructions": "First make the Hollandaise sauce. Put the lemon juice and vinegar in a small bowl, add the egg yolks and whisk with a balloon whisk until light and frothy. Place the bowl over a pan of simmering water and whisk until mixture thickens. Gradually add the butter, whisking constantly until thick – if it looks like it might be splitting, then whisk off the heat for a few mins. Season and keep warm.\r\n\r\nTo poach the eggs, bring a large pan of water to the boil and add the vinegar. Lower the heat so that the water is simmering gently. Stir the water so you have a slight whirlpool, then slide in the eggs one by one. Cook each for about 4 mins, then remove with a slotted spoon.\r\n\r\nLightly toast and butter the muffins, then put a couple of slices of salmon on each half. Top each with an egg, spoon over some Hollandaise and garnish with chopped chives.",
          "strMealThumb": "https://www.themealdb.com/images/media/meals/1550440197.jpg",
          "strTags": "Bun,Brunch",
          "strYoutube": "https://www.youtube.com/watch?v=Woiiet4vQ58",
          "strIngredient1": "Eggs",
          "strIngredient2": "White Wine Vinegar",
          "strIngredient3": "English Muffins",
          "strIngredient4": "Butter",
          "strIngredient5": "Smoked Salmon",
          "strIngredient6": "Lemon Juice",
          "strIngredient7": "White Wine Vinegar",
          "strIngredient8": "Egg",
          "strIngredient9": "Unsalted Butter",
          "strIngredient10": "",
          "strIngredient11": "",
          "strIngredient12": "",
          "strIngredient13": "",
          "strIngredient14": "",
          "strIngredient15": "",
          "strIngredient16": "",
          "strIngredient17": "",
          "strIngredient18": "",
          "strIngredient19": "",
          "strIngredient20": "",
          "strMeasure1": "4",
          "strMeasure2": "2 tbs",
          "strMeasure3": "2",
          "strMeasure4": "To serve",
          "strMeasure5": "8 slices",
          "strMeasure6": "2 tsp",
          "strMeasure7": "2 tsp",
          "strMeasure8": "3 Yolkes",
          "strMeasure9": "125g",
          "strMeasure10": " ",
          "strMeasure11": " ",
          "strMeasure12": " ",
          "strMeasure13": " ",
          "strMeasure14": " ",
          "strMeasure15": " ",
          "strMeasure16": " ",
          "strMeasure17": " ",
          "strMeasure18": " ",
          "strMeasure19": " ",
          "strMeasure20": " ",
          "strSource": "https://www.bbcgoodfood.com/recipes/73606/eggs-benedict-with-smoked-salmon-and-chives",
          "dateModified": null
      },
      {
          "idMeal": "52959",
          "strMeal": "Baked salmon with fennel & tomatoes",
          "strDrinkAlternate": null,
          "strCategory": "Seafood",
          "strArea": "British",
          "strInstructions": "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
          "strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
          "strTags": "Paleo,Keto,HighFat,Baking,LowCarbs",
          "strYoutube": "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
          "strIngredient1": "Fennel",
          "strIngredient2": "Parsley",
          "strIngredient3": "Lemon",
          "strIngredient4": "Cherry Tomatoes",
          "strIngredient5": "Olive Oil",
          "strIngredient6": "Salmon",
          "strIngredient7": "Black Olives",
          "strIngredient8": "",
          "strIngredient9": "",
          "strIngredient10": "",
          "strIngredient11": "",
          "strIngredient12": "",
          "strIngredient13": "",
          "strIngredient14": "",
          "strIngredient15": "",
          "strIngredient16": "",
          "strIngredient17": "",
          "strIngredient18": "",
          "strIngredient19": "",
          "strIngredient20": "",
          "strMeasure1": "2 medium",
          "strMeasure2": "2 tbs chopped",
          "strMeasure3": "Juice of 1",
          "strMeasure4": "175g",
          "strMeasure5": "1 tbs",
          "strMeasure6": "350g",
          "strMeasure7": "to serve",
          "strMeasure8": "",
          "strMeasure9": "",
          "strMeasure10": "",
          "strMeasure11": "",
          "strMeasure12": "",
          "strMeasure13": "",
          "strMeasure14": "",
          "strMeasure15": "",
          "strMeasure16": "",
          "strMeasure17": "",
          "strMeasure18": "",
          "strMeasure19": "",
          "strMeasure20": "",
          "strSource": "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
          "dateModified": null
      }
  ]
};

export default recipesData;
